config/routes.rb
Rails.application.routes.draw do
  root 'scores#home'
  get 'recent', to: 'scores#recent', as: 'recent_scores'
  get 'recentwrs', to: 'scores#recent_wrs', as: 'recent_wrs'
  get 'map/:map', to: 'scores#map', as: 'map'
  get 'player/:player_id', to: 'scores#player', as: 'player'
  get 'player', to: redirect('players')
  get 'players', to: 'players#index', as: 'players'
  get 'mostwrs', to: 'players#most_wrs', as: 'most_wrs'
  get 'players/autocomplete_player_name', as: 'players_autocomplete'
  get 'servers', to: 'servers#show', as: 'servers'

  apipie
  namespace :api, defaults: { format: 'json' } do
    get 'maps', to: 'maps_api#maps'
    get 'map/:map', to: 'scores_api#map'
    get 'player/:player_id', to: 'scores_api#player'
    post 'new', to: 'scores_new#new'
    root to: redirect('/apidoc'), via: :all
    match '*path', to: redirect('/apidoc'), via: :all
  end
end

app/views/layouts/_footer.html.slim
footer
  .row
    .col-lg-12
      ul.list-inline
        li
          a href='https://discord.gg/VFYwJCs' Discord
        li
          a href='https://github.com/QLRace' GitHub
        li
          a href='/apidoc'  API
        li
          a href='https://status.qlrace.com' Status
        li.pull-right
          a href='#top' Back to top
      ul.list-unstyled
        li
          | Made by #{link_to 'Christopher Stewart', 'https://github.com/cstewart90'}
          |  aka #{link_to 'kanzo', player_path(76561197986657050)}.
        li
          | Code released under the
          |  #{link_to 'MIT License', 'https://github.com/QLRace/QLRace/blob/master/LICENSE'}.

app/views/layouts/_head.html.slim
head
  meta charset='utf-8'
  meta content="IE=edge" http-equiv="X-UA-Compatible"
  meta name='viewport' content='width=device-width, initial-scale=1.0'
  title = full_title(yield(:title))
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': true
  = javascript_include_tag 'application', 'data-turbolinks-track': true, async: Rails.env.production?
  = csrf_meta_tags

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target='#bs-example-navbar-collapse-1' data-toggle='collapse' type='button'
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'QLRace', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            | Records
            span.caret
          ul.dropdown-menu
            li = link_to 'Recent Records', recent_scores_path
            li = link_to 'Recent World Records', recent_wrs_path
            li = link_to 'Most World Records', most_wrs_path
        li
          = link_to 'Players', players_path
        li
          = link_to 'Servers', servers_path
      ul.nav.navbar-right
        = render 'layouts/search_players'

app/views/layouts/_search_players.html.slim
= form_tag(players_path, method: 'get', id: 'search-form', class: 'navbar-form navbar-right') do
  = text_field_tag :search, params[:search], placeholder: 'Find Player', class: 'form-control',
    'data-autocomplete': players_autocomplete_path
  = submit_tag 'Search', name: nil, class: 'btn btn-default'

app/views/layouts/_server_info.html.slim
.panel.panel-default
  .panel-heading
    = server[:name]
  .panel-body
    ul.list-unstyled
      li IP: #{link_to server[:address], "steam://connect/#{server[:address]}"}
      li Map: #{link_to server[:map], map_path(server[:map])}
      li Players: #{server[:num_players]}
      li
        - if server[:players].present?
          table.table.table-striped.table-hover.table-xtra-condensed
            thead
              tr
                th Name
                th.text-right Time
            tbody
              - server[:players].each do |player|
                tr
                  td = player[:name]
                  td.text-right = time_string(player[:time])

app/views/layouts/_switches.html.slim
#switches.col-md-4.col-sm-6.pull-right-mode
  .panel.panel-default
    .panel-heading Mode
    .panel-body
      ul.list-inline
        input type='checkbox' name='physics' data-label-text='Physics' data-on-text='Turbo' data-off-text='Classic' data-inverse='true' title="physics"
        .pull-right
          input type='checkbox' name='weapons' data-label-text='Weapons' data-inverse='true' title='weapons'

app/views/layouts/apidoc.html.slim
- provide(:title, 'API Documentation')

doctype html
html lang='en'
  = render 'layouts/head'
  body
    = render 'layouts/navbar'
    .container
      .row
        .container
          = yield
          = render 'disqus' if Apipie.configuration.use_disqus?
          = render 'layouts/footer'

app/views/layouts/application.html.slim
doctype html
html lang='en'
  = render 'layouts/head'
  body
    = render 'layouts/navbar'
    .container
      = yield
      = render 'layouts/footer'